name: Update badges
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: joao-vitor-de-araujo-sant-anna
          CREDLY_SORT: POPULAR
          BADGE_SIZE: 110X110
          NUMBER_LAST_BADGES: 48
