name: Update badges
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: joao-vitor-de-araujo-sant-anna # optional, but default will use the same from github
          CREDLY_SORT: POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: the resolution to the badges images # optional, 110x110 default
          NUMBER_LAST_BADGES: the maximum last badges to show # optional, will show the 48 in the first page
